language: go

services:
  - postgresql
  - mysql

before_script:
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database dbpopulate_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database dbpopulate_test;'; fi"
  - go get -t -v ./...

go:
  - 1.4
  - 1.5
  - 1.6

env:
  - DB=sqlite3 DATABASE_URL="sqlite3://:memory:"
  - DB=postgres DATABASE_URL="postgres://postgres@localhost/dbpopulate_test?sslmode=disable"
  - DB=mysql DATABASE_URL="mysql://root@tcp(localhost:3306)/dbpopulate_test"
